package com.pwc.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;



import com.pwc.domain.core.Check_List_Maintenance_Master;

import com.pwc.dao.mysql.Check_List_Maintenance_Master_Default_ActivityDao;

import com.pwc.domain.core.GpUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Check_List_Maintenance_Master_Default_ActivityService")
public class Check_List_Maintenance_Master_Default_ActivityService extends GpBaseService  {

	Check_List_Maintenance_Master_Default_ActivityDao Check_List_Maintenance_Master_Default_Activity_dao;

	Questions_Default_ActivityService Questions_Default_ActivityService;

	Answers_Default_ActivityService Answers_Default_ActivityService;


	public Check_List_Maintenance_Master_Default_ActivityDao get_Check_List_Maintenance_Master_Default_Activity_dao() {
		return Check_List_Maintenance_Master_Default_Activity_dao;
	}


	@Resource(name="Check_List_Maintenance_Master_Default_ActivityDao")
	public void set_Check_List_Maintenance_Master_Default_Activity_dao(Check_List_Maintenance_Master_Default_ActivityDao Check_List_Maintenance_Master_Default_Activity_dao) {
		this.Check_List_Maintenance_Master_Default_Activity_dao = Check_List_Maintenance_Master_Default_Activity_dao;
	}


	public Questions_Default_ActivityService get_Questions_Default_ActivityService() {
		return Questions_Default_ActivityService;
	}


	@Resource(name="Questions_Default_ActivityService")
	public void set_Questions_Default_ActivityService(Questions_Default_ActivityService Questions_Default_ActivityService) {
		this.Questions_Default_ActivityService = Questions_Default_ActivityService;
	}


	public Answers_Default_ActivityService get_Answers_Default_ActivityService() {
		return Answers_Default_ActivityService;
	}


	@Resource(name="Answers_Default_ActivityService")
	public void set_Answers_Default_ActivityService(Answers_Default_ActivityService Answers_Default_ActivityService) {
		this.Answers_Default_ActivityService = Answers_Default_ActivityService;
	}



	//auths not ready at this time
	public Check_List_Maintenance_Master create_check_list_maintenance_master(Check_List_Maintenance_Master Check_List_Maintenance_Master, GpUser user) throws Exception {


		try{
			Check_List_Maintenance_Master the_Check_List_Maintenance_Master;

			the_Check_List_Maintenance_Master = Check_List_Maintenance_Master_Default_Activity_dao.create_check_list_maintenance_master(Check_List_Maintenance_Master, user);

			return the_Check_List_Maintenance_Master;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public Check_List_Maintenance_Master update_check_list_maintenance_master(Check_List_Maintenance_Master Check_List_Maintenance_Master, GpUser user) throws Exception {


		try{
			Check_List_Maintenance_Master the_Check_List_Maintenance_Master;

			the_Check_List_Maintenance_Master = Check_List_Maintenance_Master_Default_Activity_dao.update_check_list_maintenance_master(Check_List_Maintenance_Master, user);

			return the_Check_List_Maintenance_Master;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public Check_List_Maintenance_Master check_list_maintenance_master_search_for_update(long id, GpUser user) throws Exception {


		try{
			Check_List_Maintenance_Master the_Check_List_Maintenance_Master;

			the_Check_List_Maintenance_Master = Check_List_Maintenance_Master_Default_Activity_dao.check_list_maintenance_master_search_for_update(id, user);
			the_Check_List_Maintenance_Master.setQuestions(Questions_Default_ActivityService.get_questions_by_parent_id(the_Check_List_Maintenance_Master.getId()));
			the_Check_List_Maintenance_Master.setAnswers(Answers_Default_ActivityService.get_answers_by_parent_id(the_Check_List_Maintenance_Master.getId(),0,0).get(0));


			return the_Check_List_Maintenance_Master;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public String  delete_check_list_maintenance_master(long id, GpUser user) throws Exception {


		try{
			String method_return_message;

			method_return_message = Check_List_Maintenance_Master_Default_Activity_dao.delete_check_list_maintenance_master(id, user);
			Questions_Default_ActivityService.delete_questions_by_parent_id(id);
			Answers_Default_ActivityService.delete_answers_by_parent_id(id,0,0);


			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public ArrayList<Check_List_Maintenance_Master> get_all_check_list_maintenance_master() throws Exception {


		try{
			ArrayList<Check_List_Maintenance_Master> Check_List_Maintenance_Master_list;

			Check_List_Maintenance_Master_list = Check_List_Maintenance_Master_Default_Activity_dao.get_all_check_list_maintenance_master();
			for(Check_List_Maintenance_Master Check_List_Maintenance_Master : Check_List_Maintenance_Master_list){
				Check_List_Maintenance_Master.setQuestions(Questions_Default_ActivityService.get_questions_by_parent_id(Check_List_Maintenance_Master.getId()));
			}for(Check_List_Maintenance_Master Check_List_Maintenance_Master : Check_List_Maintenance_Master_list){
				Check_List_Maintenance_Master.setAnswers(Answers_Default_ActivityService.get_answers_by_parent_id(Check_List_Maintenance_Master.getId(),0,0).get(0));
			}

			return Check_List_Maintenance_Master_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}




}