package com.pwc.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;



import com.pwc.domain.core.In_flight_checklists;

import com.pwc.dao.mysql.In_flight_checklists_Default_ActivityDao;

import com.pwc.domain.core.GpUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("In_flight_checklists_Default_ActivityService")
public class In_flight_checklists_Default_ActivityService extends GpBaseService  {

	In_flight_checklists_Default_ActivityDao In_flight_checklists_Default_Activity_dao;

	Answers_Default_ActivityService Answers_Default_ActivityService;


	public In_flight_checklists_Default_ActivityDao get_In_flight_checklists_Default_Activity_dao() {
		return In_flight_checklists_Default_Activity_dao;
	}


	@Resource(name="In_flight_checklists_Default_ActivityDao")
	public void set_In_flight_checklists_Default_Activity_dao(In_flight_checklists_Default_ActivityDao In_flight_checklists_Default_Activity_dao) {
		this.In_flight_checklists_Default_Activity_dao = In_flight_checklists_Default_Activity_dao;
	}


	public Answers_Default_ActivityService get_Answers_Default_ActivityService() {
		return Answers_Default_ActivityService;
	}


	@Resource(name="Answers_Default_ActivityService")
	public void set_Answers_Default_ActivityService(Answers_Default_ActivityService Answers_Default_ActivityService) {
		this.Answers_Default_ActivityService = Answers_Default_ActivityService;
	}



	//auths not ready at this time
	public In_flight_checklists create_in_flight_checklists(In_flight_checklists In_flight_checklists, GpUser user) throws Exception {


		try{
			In_flight_checklists the_In_flight_checklists;

			the_In_flight_checklists = In_flight_checklists_Default_Activity_dao.create_in_flight_checklists(In_flight_checklists, user);

			return the_In_flight_checklists;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public In_flight_checklists update_in_flight_checklists(In_flight_checklists In_flight_checklists, GpUser user) throws Exception {


		try{
			In_flight_checklists the_In_flight_checklists;

			the_In_flight_checklists = In_flight_checklists_Default_Activity_dao.update_in_flight_checklists(In_flight_checklists, user);

			return the_In_flight_checklists;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public In_flight_checklists in_flight_checklists_search_for_update(long id, GpUser user) throws Exception {


		try{
			In_flight_checklists the_In_flight_checklists;

			the_In_flight_checklists = In_flight_checklists_Default_Activity_dao.in_flight_checklists_search_for_update(id, user);
			the_In_flight_checklists.setAnswers(Answers_Default_ActivityService.get_answers_by_parent_id(0,0,the_In_flight_checklists.getId()));


			return the_In_flight_checklists;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public String  delete_in_flight_checklists(long id, GpUser user) throws Exception {


		try{
			String method_return_message;

			method_return_message = In_flight_checklists_Default_Activity_dao.delete_in_flight_checklists(id, user);
			Answers_Default_ActivityService.delete_answers_by_parent_id(0,0,id);


			return method_return_message;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	public ArrayList<In_flight_checklists> get_all_in_flight_checklists() throws Exception {


		try{
			ArrayList<In_flight_checklists> In_flight_checklists_list;

			In_flight_checklists_list = In_flight_checklists_Default_Activity_dao.get_all_in_flight_checklists();
			for(In_flight_checklists In_flight_checklists : In_flight_checklists_list){
				In_flight_checklists.setAnswers(Answers_Default_ActivityService.get_answers_by_parent_id(0,0,In_flight_checklists.getId()));
			}

			return In_flight_checklists_list;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;



	}




}