/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

DROP DATABASE IF EXISTS pwctest;

CREATE DATABASE pwctest
DEFAULT CHARACTER SET utf8
COLLATE utf8_general_ci;

