/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/


USE pwctest;

CREATE TABLE GpAuthority (id bigint(20) NOT NULL AUTO_INCREMENT, authority varchar(255) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
INSERT INTO GpAuthority VALUES (1,'GpUser');
INSERT INTO GpAuthority VALUES (2,'GpAdmin');
CREATE TABLE GpUser (id bigint(20) NOT NULL AUTO_INCREMENT,accestype varchar(255) DEFAULT NULL,firstName varchar(255) DEFAULT NULL,languagepreference varchar(255) DEFAULT NULL,lastName varchar(255) DEFAULT NULL,lastaccess datetime DEFAULT NULL,licenseid varchar(255) DEFAULT NULL,middleName varchar(255) DEFAULT NULL,mustresetpassword varchar(255) DEFAULT NULL,newuser bit(1) DEFAULT NULL,password varchar(255) DEFAULT NULL,phonenumber varchar(255) DEFAULT NULL, primaryemail varchar(255) DEFAULT NULL, screenname varchar(255) DEFAULT NULL, startdate datetime DEFAULT NULL, username varchar(255) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
INSERT INTO GpUser VALUES (1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','12345',NULL,NULL,NULL,NULL,'test');
INSERT INTO GpUser VALUES (2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','12345',NULL,NULL,NULL,NULL,'admin');
CREATE TABLE GpUser_GpAuthority ( GpUser_id bigint(20) NOT NULL, roles_id bigint(20) NOT NULL, PRIMARY KEY (GpUser_id,roles_id), CONSTRAINT FK_c7kyumqvtqtl74s6ci1vkhywp FOREIGN KEY (GpUser_id) REFERENCES GpUser (id), CONSTRAINT FK_qqk29t20hlrhy5v62t5jrxdkk FOREIGN KEY (roles_id) REFERENCES GpAuthority (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO GpUser_GpAuthority VALUES (1,1);
INSERT INTO GpUser_GpAuthority VALUES (2,2);

CREATE TABLE Check_List_Maintenance_Master(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
name varchar(255),
description varchar(255),
work_flow_status varchar(255),
territory varchar(255),
check_list_version bigint(19),
version_date Date,
approved_by varchar(255),
current_jason_state varchar(255),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Questions(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
type varchar(255),
answer_type varchar(255),
question varchar(255),
tree_position varchar(255),
Check_List_Maintenance_Master_id bigint(19) NOT NULL,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Answers(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
tree_position varchar(255),
answer varchar(255),
Check_List_Maintenance_Master_id bigint(19) NOT NULL UNIQUE,
Questions_id bigint(19) NOT NULL UNIQUE,
In_flight_checklists_id bigint(19) NOT NULL,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE In_flight_checklists(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
status varchar(255),
collaborators varchar(255),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
