package com.pwc.controller;

import java.util.ArrayList;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.pwc.domain.core.In_flight_checklists;

import com.pwc.service.In_flight_checklists_Default_ActivityService;



/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/In_flight_checklists_Default_Activity", description = "In_flight_checklists_Default_Activity of In_flight_checklists_Default_Activity", 
produces = "application/json")

@Controller("In_flight_checklists_Default_ActivityController")
@RequestMapping("/In_flight_checklists_Default_Activity")
public class In_flight_checklists_Default_ActivityController extends GpBaseController {


	In_flight_checklists_Default_ActivityService In_flight_checklists_Default_Activity_service;


	public In_flight_checklists_Default_ActivityService get_In_flight_checklists_Default_Activity_service() {
		return In_flight_checklists_Default_Activity_service;
	}


	@Resource(name="In_flight_checklists_Default_ActivityService")
	public void set_In_flight_checklists_Default_Activity_service(In_flight_checklists_Default_ActivityService In_flight_checklists_Default_Activity_service) {
		this.In_flight_checklists_Default_Activity_service = In_flight_checklists_Default_Activity_service;
	}




	//auths not ready at this time


	@ApiOperation(value = "/create_In_flight_checklists", httpMethod = "POST",
	notes = "creates a noun of In_flight_checklists", 
	response = In_flight_checklists.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.POST,value = "/create_In_flight_checklists" ,headers="Accept=application/json")
    @ResponseBody
	public In_flight_checklists create_In_flight_checklists(@RequestBody In_flight_checklists the_In_flight_checklists) throws Exception {

		In_flight_checklists a_In_flight_checklists;

		a_In_flight_checklists = In_flight_checklists_Default_Activity_service.create_in_flight_checklists(the_In_flight_checklists, super.getUser());

		return a_In_flight_checklists;

	}

	//auths not ready at this time


	@ApiOperation(value = "/update_In_flight_checklists", httpMethod = "PUT",
	notes = "updates a noun of In_flight_checklists", 
	response = In_flight_checklists.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.PUT,value = "/update_In_flight_checklists" ,headers="Accept=application/json")
    @ResponseBody
	public In_flight_checklists update_In_flight_checklists(@RequestBody In_flight_checklists the_In_flight_checklists) throws Exception {

		In_flight_checklists a_In_flight_checklists;

		a_In_flight_checklists = In_flight_checklists_Default_Activity_service.update_in_flight_checklists(the_In_flight_checklists, super.getUser());

		return a_In_flight_checklists;

	}

	//auths not ready at this time


	@ApiOperation(value = "/search_for_update_In_flight_checklists/{In_flight_checklists_id}", httpMethod = "GET",
	notes = "updates a noun of In_flight_checklists", 
	response = In_flight_checklists.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_In_flight_checklists/{In_flight_checklists_id}" ,headers="Accept=application/json")
    @ResponseBody
	public In_flight_checklists search_for_update_In_flight_checklists(@PathVariable("In_flight_checklists_id")long In_flight_checklists_id) throws Exception {

		In_flight_checklists the_In_flight_checklists = new In_flight_checklists();

		the_In_flight_checklists = In_flight_checklists_Default_Activity_service.in_flight_checklists_search_for_update(In_flight_checklists_id, super.getUser());

		return the_In_flight_checklists;

	}

	//auths not ready at this time


	@ApiOperation(value = "/delete_In_flight_checklists/{In_flight_checklists_id}", httpMethod = "DELETE",
	notes = "deletes a noun of In_flight_checklists", 
	response = In_flight_checklists.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_In_flight_checklists/{In_flight_checklists_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_In_flight_checklists(@PathVariable("In_flight_checklists_id")long In_flight_checklists_id) throws Exception {

		String service_return_msg = "";

		service_return_msg = In_flight_checklists_Default_Activity_service.delete_in_flight_checklists(In_flight_checklists_id, super.getUser());

		return service_return_msg;

	}

	//auths not ready at this time


	@ApiOperation(value = "/get_all_In_flight_checklists", httpMethod = "GET",
	notes = "special search that gets all values of In_flight_checklists", 
	response = In_flight_checklists.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.GET,value = "/get_all_In_flight_checklists" ,headers="Accept=application/json")
    @ResponseBody
	public ArrayList<In_flight_checklists> get_all_In_flight_checklists() throws Exception {

		ArrayList<In_flight_checklists> In_flight_checklists_list = new ArrayList<In_flight_checklists>();

		In_flight_checklists_list = In_flight_checklists_Default_Activity_service.get_all_in_flight_checklists();

		return In_flight_checklists_list;

	}




}