package com.pwc.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;



import com.pwc.domain.core.Answers;
import com.pwc.domain.core.GpUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("Answers_Default_ActivityDao")
public class Answers_Default_ActivityDao   {

	private Log log = LogFactory.getLog(getClass());

	@Value("${create_Answers.sql}")
	private String create_Answers;
	@Value("${search_for_update_Answers.sql}")
	private String search_for_update_Answers;
	@Value("${update_Answers.sql}")
	private String update_Answers;
	@Value("${delete_Answers.sql}")
	private String delete_Answers;
	@Value("${get_all_Answers.sql}")
	private String get_all_Answers;
	@Value("${get_by_parent_id_Answers.sql}")
	private String get_by_parent_id_Answers;
	@Value("${delete_by_parent_id_Answers.sql}")
	private String delete_by_parent_id_Answers;


    @PersistenceContext
	EntityManager entityManager;



	//auths not ready at this time
	public Answers answers_search_for_update(long id, GpUser user) throws Exception {


		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_Answers,Answers.class)

			.setParameter("id", id);;

			ArrayList<Answers> Answers_list =	(ArrayList<Answers>)result.getResultList();

			if(Answers_list  == null){
				throw new Exception("no Answers found");
			}

			return (Answers) Answers_list.get(0);

		}catch(Exception e){

			new Exception(e.toString());  // this needs to be changed

		}
		return null;


	}

	//auths not ready at this time
	public ArrayList<Answers> get_all_answers() throws Exception {


		try{

			Query result =  entityManager.
			createNativeQuery(get_all_Answers,Answers.class)

;

			ArrayList<Answers> Answers_list =	(ArrayList<Answers>)result.getResultList();

			if(Answers_list .size() < 1){
				throw new Exception("no Answers found");
			}

			return (ArrayList<Answers>) Answers_list;

		}catch(Exception e){

			new Exception(e.toString());  // this needs to be changed

		}
		return null;


	}

	//auths not ready at this time
	public ArrayList<Answers> get_answers_by_parent_id(long Check_List_Maintenance_Master_id,long Questions_id,long In_flight_checklists_id) throws Exception {


		try{

			Query result =  entityManager.
			createNativeQuery(get_by_parent_id_Answers,Answers.class)

			.setParameter("Check_List_Maintenance_Master_id", Check_List_Maintenance_Master_id == 0 ? "%%" : Check_List_Maintenance_Master_id).setParameter("Questions_id", Questions_id == 0 ? "%%" : Questions_id).setParameter("In_flight_checklists_id", In_flight_checklists_id == 0 ? "%%" : In_flight_checklists_id);

			ArrayList<Answers> Answers_list =	(ArrayList<Answers>)result.getResultList();

			if(Answers_list .size() < 1){
				throw new Exception("no Answers found");
			}

			return (ArrayList<Answers>) Answers_list;

		}catch(Exception e){

			new Exception(e.toString());  // this needs to be changed

		}
		return null;


	}



	//auths not ready at this time
	@Transactional
	public Answers create_answers(Answers Answers, GpUser user) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(create_Answers)
			.setParameter("tree_position", Answers.getTree_position())
			.setParameter("answer", Answers.getAnswer())
			.setParameter("Check_List_Maintenance_Master_id", Answers.getCheck_List_Maintenance_Master_id())
			.setParameter("Questions_id", Answers.getQuestions_id())
			.setParameter("In_flight_checklists_id", Answers.getIn_flight_checklists_id())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					Answers.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			return Answers;

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	@Transactional
	public Answers update_answers(Answers Answers, GpUser user) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(update_Answers)
			.setParameter("id", Answers.getId())
			.setParameter("tree_position", Answers.getTree_position())
			.setParameter("answer", Answers.getAnswer())
			.setParameter("Check_List_Maintenance_Master_id", Answers.getCheck_List_Maintenance_Master_id())
			.setParameter("Questions_id", Answers.getQuestions_id())
			.setParameter("In_flight_checklists_id", Answers.getIn_flight_checklists_id())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			return Answers;

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	@Transactional
	public String  delete_answers(long id, GpUser user) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(delete_Answers)
			.setParameter("id", id);

			query.executeUpdate();

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	@Transactional
	public String  delete_answers_by_parent_id(long Check_List_Maintenance_Master_id,long Questions_id,long In_flight_checklists_id) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(delete_by_parent_id_Answers)
			.setParameter("Check_List_Maintenance_Master_id", Check_List_Maintenance_Master_id == 0 ? "%%" : Check_List_Maintenance_Master_id).setParameter("Questions_id", Questions_id == 0 ? "%%" : Questions_id).setParameter("In_flight_checklists_id", In_flight_checklists_id == 0 ? "%%" : In_flight_checklists_id);

			query.executeUpdate();

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}



}