package com.pwc.domain.core;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;


@Entity

@Table(name="Answers")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel( value = "Answers", description = "repository for the answers given for to a checklist" )
@JsonInclude(Include.NON_NULL)
public class Answers  {

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	long Updated_by;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Tree_position;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Answer;


	@ApiModelProperty( value = "parent id", required = true )
	@Column
 	long Check_List_Maintenance_Master_id;


	@ApiModelProperty( value = "parent id", required = true )
	@Column
 	long Questions_id;


	@ApiModelProperty( value = "parent id", required = true )
	@Column
 	long In_flight_checklists_id;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setTree_position(String Tree_position) {
		this.Tree_position = Tree_position;
	}


	public String getTree_position() {
		return Tree_position;
	}

	public void setAnswer(String Answer) {
		this.Answer = Answer;
	}


	public String getAnswer() {
		return Answer;
	}

	public void setCheck_List_Maintenance_Master_id(long Check_List_Maintenance_Master_id) {
		this.Check_List_Maintenance_Master_id = Check_List_Maintenance_Master_id;
	}


	public long getCheck_List_Maintenance_Master_id() {
		return Check_List_Maintenance_Master_id;
	}

	public void setQuestions_id(long Questions_id) {
		this.Questions_id = Questions_id;
	}


	public long getQuestions_id() {
		return Questions_id;
	}

	public void setIn_flight_checklists_id(long In_flight_checklists_id) {
		this.In_flight_checklists_id = In_flight_checklists_id;
	}


	public long getIn_flight_checklists_id() {
		return In_flight_checklists_id;
	}




}