package com.pwc.domain.core;

import java.util.List;

import javax.persistence.Transient;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;


@Entity

@Table(name="Check_List_Maintenance_Master")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel( value = "Check_List_Maintenance_Master", description = "maintains the master records for a checklist that is being created or updated" )
@JsonInclude(Include.NON_NULL)
public class Check_List_Maintenance_Master  {

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	long Updated_by;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Name;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Description;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Work_flow_status;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Territory;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	long Check_list_version;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Version_date;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Approved_by;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Current_jason_state;


	@ApiModelProperty( value = "Parent noun", required = true )
	@Transient
 	List<Questions> Questions;


	@ApiModelProperty( value = "Parent noun", required = true )
	@Transient
 	Answers Answers;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setName(String Name) {
		this.Name = Name;
	}


	public String getName() {
		return Name;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}


	public String getDescription() {
		return Description;
	}

	public void setWork_flow_status(String Work_flow_status) {
		this.Work_flow_status = Work_flow_status;
	}


	public String getWork_flow_status() {
		return Work_flow_status;
	}

	public void setTerritory(String Territory) {
		this.Territory = Territory;
	}


	public String getTerritory() {
		return Territory;
	}

	public void setCheck_list_version(long Check_list_version) {
		this.Check_list_version = Check_list_version;
	}


	public long getCheck_list_version() {
		return Check_list_version;
	}

	public void setVersion_date(String Version_date) {
		this.Version_date = Version_date;
	}


	public String getVersion_date() {
		return Version_date;
	}

	public void setApproved_by(String Approved_by) {
		this.Approved_by = Approved_by;
	}


	public String getApproved_by() {
		return Approved_by;
	}

	public void setCurrent_jason_state(String Current_jason_state) {
		this.Current_jason_state = Current_jason_state;
	}


	public String getCurrent_jason_state() {
		return Current_jason_state;
	}

	public void setQuestions(List<Questions> Questions) {
		this.Questions = Questions;
	}


	public List<Questions> getQuestions() {
		return Questions;
	}

	public void setAnswers(Answers Answers) {
		this.Answers = Answers;
	}


	public Answers getAnswers() {
		return Answers;
	}




}