package com.pwc.domain.core;

import java.util.List;

import javax.persistence.Transient;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;


@Entity

@Table(name="In_flight_checklists")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel( value = "In_flight_checklists", description = "repository for checklists that a client starts to answer" )
@JsonInclude(Include.NON_NULL)
public class In_flight_checklists  {

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	long Updated_by;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Status;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Collaborators;


	@ApiModelProperty( value = "Parent noun", required = true )
	@Transient
 	List<Answers> Answers;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setStatus(String Status) {
		this.Status = Status;
	}


	public String getStatus() {
		return Status;
	}

	public void setCollaborators(String Collaborators) {
		this.Collaborators = Collaborators;
	}


	public String getCollaborators() {
		return Collaborators;
	}

	public void setAnswers(List<Answers> Answers) {
		this.Answers = Answers;
	}


	public List<Answers> getAnswers() {
		return Answers;
	}




}