package com.pwc.domain.core;

import javax.persistence.Transient;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;


@Entity

@Table(name="Questions")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel( value = "Questions", description = "maintains the questions for a checklist that is in the process of being created or maintained" )
@JsonInclude(Include.NON_NULL)
public class Questions  {

	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	long Id;


	@ApiModelProperty( value = "created date", required = true )
	@Column
 	String Created_date;


	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	long Created_by;


	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	String Updated_date;


	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	long Updated_by;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Type;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Answer_type;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Question;


	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Tree_position;


	@ApiModelProperty( value = "parent id", required = true )
	@Column
 	long Check_List_Maintenance_Master_id;


	@ApiModelProperty( value = "Parent noun", required = true )
	@Transient
 	Answers Answers;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setType(String Type) {
		this.Type = Type;
	}


	public String getType() {
		return Type;
	}

	public void setAnswer_type(String Answer_type) {
		this.Answer_type = Answer_type;
	}


	public String getAnswer_type() {
		return Answer_type;
	}

	public void setQuestion(String Question) {
		this.Question = Question;
	}


	public String getQuestion() {
		return Question;
	}

	public void setTree_position(String Tree_position) {
		this.Tree_position = Tree_position;
	}


	public String getTree_position() {
		return Tree_position;
	}

	public void setCheck_List_Maintenance_Master_id(long Check_List_Maintenance_Master_id) {
		this.Check_List_Maintenance_Master_id = Check_List_Maintenance_Master_id;
	}


	public long getCheck_List_Maintenance_Master_id() {
		return Check_List_Maintenance_Master_id;
	}

	public void setAnswers(Answers Answers) {
		this.Answers = Answers;
	}


	public Answers getAnswers() {
		return Answers;
	}




}